BattleDome_Text_Potential1::
	.string "Der Anwärter auf den Titel des Champs!$"

BattleDome_Text_Potential2::
	.string "Der sichere Finalist.$"

BattleDome_Text_Potential3::
	.string "Ein Kandidat für die ersten Drei.$"

BattleDome_Text_Potential4::
	.string "Ein Kandidat, der Erster werden könnte.$"

BattleDome_Text_Potential5::
	.string "Ein Team mit riesigem Potenzial.$"

BattleDome_Text_Potential6::
	.string "Die unbekannte Größe dieses Turniers.$"

BattleDome_Text_Potential7::
	.string "Ein Team, besser als der Durchschnitt.$"

BattleDome_Text_Potential8::
	.string "Das durchschnittliche Team.$"

BattleDome_Text_Potential9::
	.string "Team mit durchschnittlichem Potenzial.$"

BattleDome_Text_Potential10::
	.string "Schwächer als der Durchschnitt.$"

BattleDome_Text_Potential11::
	.string "Team, das nach dem ersten Sieg strebt.$"

BattleDome_Text_Potential12::
	.string "Ein Sieg und dieses Team wäre stolz.$"

BattleDome_Text_Potential13::
	.string "Alles in allem ein schwaches Team.$"

BattleDome_Text_Potential14::
	.string "Team mit schwachem Potenzial.$"

BattleDome_Text_Potential15::
	.string "Ein Team, das wohl nicht gewinnen wird.$"

BattleDome_Text_Potential16::
	.string "Dieses Team wird nicht gewinnen.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "Die perfekten, unschlagbaren Stars.$"

BattleDome_Text_StyleRiskDisaster::
	.string "Hat einen Hang zur Katastrophe.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Hält lange Kämpfe spielend durch.$"

BattleDome_Text_StyleVariesTactics::
	.string "Passt Taktik an den Gegner an.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Starke Form eines Gewinners erkennbar.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Setzt manchmal seltene Attacken ein.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Setzt verwirrende Attacken ein.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Behält im Kampf ständig KP im Auge.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Gut im Bewahren von Kraft.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Gut im Schwächen von Gegnern.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Verlässt sich auf das Glück.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Greift hoheitsvoll an.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Liebt starke, AP-schwache Attacken.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Schwächt und greift dann an.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Erträgt kämpfend alle Angriffe.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Verwirrt den Gegner emotional.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Setzt starke, forsche Attacken ein.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Setzt aggressive, starke Attacken ein.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Kämpft und duckt sich dabei clever.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Seine Attacken verärgern den Gegner.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Setzt viele gängige Attacken ein.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Setzt starke Attacken-Combos ein.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Attacken mit hoher Trefferquote.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Setzt kühn spektakuläre Attacken ein.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Setzt auf Offensive statt Defensive.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Setzt auf Defensive statt Offensive.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Schneller Angriff mit starken Attacken.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Attacken mit zusätzlicher Wirkung.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Gut ausbalancierter Mix von Attacken.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Dies ist Beispiel 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Dies ist Beispiel 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Dies ist Beispiel 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Dies ist Beispiel 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Legt Wert auf KP und ANGRIFF.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Legt Wert auf KP und VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Legt Wert auf KP und INITIATIVE.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Legt Wert auf KP und SP. ANGR.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Legt Wert auf KP und SP. VERT.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Legt Wert auf ANGRIFF und VERT.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Legt Wert auf ANGRIFF und INITIATIVE.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Legt Wert auf ANGRIFF und SP. ANGR.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Legt Wert auf ANGRIFF und SP. VERT.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Legt Wert auf VERT. und INIT.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Legt Wert auf VERT. und SP. ANGR.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Legt Wert auf VERT. und SP. VERT.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Legt Wert auf INIT. und SP. ANGR.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Legt Wert auf INIT. und SP. VERT.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Legt Wert auf SP. ANGR. u. SP. VERT.$"

BattleDome_Text_EmphasizesHP::
	.string "Legt Wert auf KP.$"

BattleDome_Text_EmphasizesAtk::
	.string "Legt Wert auf ANGRIFF.$"

BattleDome_Text_EmphasizesDef::
	.string "Legt Wert auf VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Legt Wert auf INITIATIVE.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Legt Wert auf SP. ANGRIFF.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Legt Wert auf SP. VERTEIDIGUNG.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Vernachlässigt KP und ANGRIFF.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Vernachlässigt KP und VERTEIDIGUNG.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Vernachlässigt KP und INITIATIVE.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Vernachlässigt KP und SP. ANGRIFF.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Vernachlässigt KP und SP. VERT.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Vernachlässigt ANGR. und VERT.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Vernachlässigt ANGR. und INIT.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Vernachlässigt ANGR. und SP. ANGR.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Vernachlässigt ANGR. und SP. VERT.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Vernachlässigt VERT. und INIT.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Vernachlässigt VERT. und SP. ANGR.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Vernachlässigt VERT. und SP. VERT.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Vernachlässigt INIT. und SP. ANGR.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Vernachlässigt INIT. und SP. VERT.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Vernachlässigt SP. ANGR. und SP. VERT.$"

BattleDome_Text_NeglectsHP::
	.string "Vernachlässigt KP.$"

BattleDome_Text_NeglectsAtk::
	.string "Vernachlässigt ANGRIFF.$"

BattleDome_Text_NeglectsDef::
	.string "Vernachlässigt VERTEIDIGUNG.$"

BattleDome_Text_NeglectsSpeed::
	.string "Vernachlässigt INITIATIVE.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Vernachlässigt SPEZ. ANGRIFF.$"

BattleDome_Text_NeglectsSpDef::
	.string "Vernachlässigt SPEZ. VERTEIDIGUNG.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Zieht POKéMON ausgewogen auf.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Lasst den Kampf beginnen!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} gewinnt mit {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} wird der Champ!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} gewinnt durch Aufgabe!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} gewinnt durch Aufgabe!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} gewinnt ohne anzugreifen!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} gewinnt ohne anzugreifen!$"

BattleDome_Text_Round1Match1::
	.string "Runde 1, Kampf 1$"

BattleDome_Text_Round1Match2::
	.string "Runde 1, Kampf 2$"

BattleDome_Text_Round1Match3::
	.string "Runde 1, Kampf 3$"

BattleDome_Text_Round1Match4::
	.string "Runde 1, Kampf 4$"

BattleDome_Text_Round1Match5::
	.string "Runde 1, Kampf 5$"

BattleDome_Text_Round1Match6::
	.string "Runde 1, Kampf 6$"

BattleDome_Text_Round1Match7::
	.string "Runde 1, Kampf 7$"

BattleDome_Text_Round1Match8::
	.string "Runde 1, Kampf 8$"

BattleDome_Text_Round2Match1::
	.string "Runde 2, Kampf 1$"

BattleDome_Text_Round2Match2::
	.string "Runde 2, Kampf 2$"

BattleDome_Text_Round2Match3::
	.string "Runde 2, Kampf 3$"

BattleDome_Text_Round2Match4::
	.string "Runde 2, Kampf 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Halbfinale Kampf 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Halbfinale Kampf 2$"

BattleDome_Text_FinalMatch::
	.string "Finale$"
