CableClub_Text_WelcomeWhichCableClubService:
	.string "Willkommen im POKéMON\n"
	.string "KABEL-CLUB!\p"
	.string "Welchen Service möchtest du\n"
	.string "nutzen?$"

CableClub_Text_WhichService:
	.string "Welchen Service möchtest du\n"
	.string "nutzen?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Tausche POKéMON mit einem\n"
	.string "Mitspieler via GBA Game Link-Kabel.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Tritt gegen einen anderen TRAINER\n"
	.string "via GBA Game Link-Kabel an.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Mit dem GBA Game Link-Kabel kannst du\n"
	.string "einen STATISTIKTAUSCH vornehmen.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Close this menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Für einen DOPPELKAMPF brauchst du\n"
	.string "mindestens zwei POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Für einen Tausch musst du mindestens\n"
	.string "zwei POKéMON bei dir haben.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Ein POKéMON, das eine {STR_VAR_1}BEERE\n"
	.string "hält, kann nicht getauscht werden.$"

gText_PleaseWaitForLink::
	.string "Bitte warten.\n"
	.string "Drücke den B-Knopf, um abzubrechen…$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Wenn die Spieler bereit sind…\n"
	.string "A-Knopf: Bestätigen\l"
	.string "B-Knopf: Abbruch$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Verbindung für {STR_VAR_1} Spieler aufbauen.\n"
	.string "A-Knopf: Bestätigen\l"
	.string "B-Knopf: Abbruch$"

gText_AwaitingLinkup::
	.string "Verbindungsaufbau…\n"
	.string "… … B-Knopf: Abbruch$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Your progress must be saved before\n"
	.string "linking. Is it okay to save?$"

CableClub_Text_PleaseEnter:
	.string "Bitte eintreten.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Bitte eintreten.$"

Text_SomeoneIsNotReadyToLink:
	.string "Ein Spieler ist noch nicht bereit\n"
	.string "für den Link.\p"
	.string "Bitte kommt wieder, wenn jeder seine\n"
	.string "Vorbereitungen getroffen hat.$"

Text_LinkErrorPleaseReset:
	.string "Verbindungsfehler…\n"
	.string "Die Kabelverbindungen überprüfen und\l"
	.string "eine erneute Verbindung herstellen.$"

Text_PlayersMadeDifferentSelections:
	.string "Die Link-Partner haben eine unter-\n"
	.string "schiedliche Auswahl getroffen.$"

CableClub_Text_PleaseVisitAgain:
	.string "Bitte komm bald wieder.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Die Anzahl der Teilnehmer ist nicht\n"
	.string "korrekt.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Ein EINZELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Ein DOPPELKAMPF kann nicht von\n"
	.string "{STR_VAR_1} Spielern geführt werden.$"

CableClub_Text_NeedFourPlayers:
	.string "Für diesen Kampfmodus werden vier\n"
	.string "Spieler benötigt.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Bitte überprüfe die Anzahl der\n"
	.string "Spieler und fange nochmals an.$"

Text_TerminateLinkConfirmation:
	.string "Wenn du den Raum verlässt, wird die\n"
	.string "Verbindung abgebrochen.\l"
	.string "Einverstanden?$"

Text_TerminateLinkPleaseWait:
	.string "Verbindung wird abgebrochen…\n"
	.string "Du wirst aus dem Raum begleitet.\l"
	.string "Bitte warten.$"

CableClub_Text_TooBusyToNotice:
	.string "Dieser TRAINER ist zu beschäftigt…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Hey! Schau dir mal den TRAINERPASS\n"
	.string "von {STR_VAR_1} an!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Hey! Schau dir mal den TRAINERPASS\n"
	.string "von {STR_VAR_1} an! Es ist ein\l"
	.string "{STR_VAR_2}PASS.$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Bitte geh in Position und beginne mit\n"
	.string "dem Kampf.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Bitte geh in Position und beginne mit\n"
	.string "dem Tausch.$"

RecordCorner_Text_ThanksForComing:
	.string "Danke für den Besuch!$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Der Eintrag auf dem TRAINERPASS wird\n"
	.string "geändert.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Ich hoffe, du kommst bald wieder vorbei.$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Es tut mir schrecklich Leid.\p"
	.string "Wir sind noch nicht auf einen\n"
	.string "Tausch mit TRAINERn aus\l"
	.string "entfernten Gebieten vorbereitet…$"

CableClub_Text_OtherTrainerNotReady:
	.string "Der andere TRAINER ist noch\n"
	.string "nicht bereit!$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Du besitzt mindestens ein POKéMON,\n"
	.string "das nicht mitgenommen werden kann.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Bitte geh in Position und warte.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} hat ein {STR_VAR_2}\n"
	.string "versandt.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Tut mir Leid, es gibt einen\n"
	.string "Verbindungsfehler.\p"
	.string "Du kannst mit den japanischen\n"
	.string "Versionen der Rubin- und Saphir-\l"
	.string "Edition keine Statistiken tauschen.\p"
	.string "Du kannst zeitgleich keine Statistiken\n"
	.string "mit der japanischen Smaragd-Edition\l"
	.string "und den außerjapanischen Rubin- und\l"
	.string "Saphir-Editionen tauschen.$"

CableClub_Text_AdapterNotConnected:
	.string "Der Drahtlose Game Boy\n"
	.string "Advance-Adapter ist nicht\l"
	.string "ordnungsgemäß angeschlossen.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Die Teilnehmer werden gebeten,\n"
	.string "zur Rezeption zu gehen.$"

@ Unused
CableClub_Text_Hello:
	.string "Hello!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Please wait.$"

CableClub_Text_YouMayTradeHere::
	.string "Hier kannst du mit deinen Freunden\n"
	.string "POKéMON tauschen.$"

CableClub_Text_YouMayBattleHere::
	.string "Hier kannst du mit deinen Freunden\n"
	.string "kämpfen.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Zwei bis fünf TRAINER können\n"
	.string "zusammen BEERENPUDER herstellen.$"

CableClub_Text_CanMixRecords::
	.string "Die Statistiken von zwei bis vier\n"
	.string "Spielern können getauscht werden.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "A guide to the WIRELESS CLUB’s\n"
	.string "various services.$"

CableClub_Text_CancelSelectedItem::
	.string "Widerruft das MENÜ.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Which battle mode would you like?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Returns to the previous step.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Um die BEERENMÜHLE benutzen\n"
	.string "zu können, musst du mindestens\l"
	.string "eine BEERE besitzen.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Um den KONNEX-KLUB betreten zu\n"
	.string "dürfen, musst du mindestens zwei\l"
	.string "POKéMON besitzen.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Ein POKéMON, das eine {STR_VAR_1}BEERE\n"
	.string "hält, darf den KONNEX-KLUB nicht\l"
	.string "betreten.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Das ist der DRAHTLOSE POKéMON\n"
	.string "KONNEX-KLUB.\p"
	.string "Leider ist dein Drahtloser Game Boy\n"
	.string "Advance-Adapter nicht\l"
	.string "ordnungsgemäß angeschlossen.\l"
	.string "Bitte komme später wieder!$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Excuse me!$"

CableClub_Text_PlayerIsWaiting:
	.string "Es scheint, als ob {STR_VAR_1} gerade\n"
	.string "spielt.\l"
	.string "Los!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Ich kann dir die Spielregeln\n"
	.string "erklären, wenn du möchtest.\p"
	.string "Welches Spiel möchtest du erklärt\n"
	.string "bekommen?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON-SPRUNG”\p"
	.string "Springe mit deinem POKéMON durch\n"
	.string "Drücken des A-Knopfs über den\l"
	.string "RANKENHIEB.\l"
	.string "Es dürfen nur kleine, circa\l"
	.string "70 cm große POKéMON\l"
	.string "teilnehmen.\l"
	.string "POKéMON, die ausschließlich\l"
	.string "schwimmen, graben oder fliegen,\l"
	.string "können nicht gut springen.\l"
	.string "Daher dürfen diese POKéMON auch\l"
	.string "nicht teilnehmen.\p"
	.string "Etwas Schönes passiert, wenn alle\n"
	.string "rechtzeitig springen.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“BEERENERNTE MIT DODRI”\p"
	.string "Bewege DODRIs drei Köpfe, um die\n"
	.string "fallenden BEEREn zu fangen.\p"
	.string "Drücke das {PLUS} Steuerkreuz nach\n"
	.string "rechts, oben oder links, um die\l"
	.string "Köpfe zu bewegen.\l"
	.string "Um an diesem Spiel teilnehmen zu\l"
	.string "dürfen, benötigst du ein DODRI.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Wenn du spielen möchtest, dann wende\n"
	.string "dich bitte an den älteren Herrn\l"
	.string "neben mir.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Hallo! Herzlich willkommen!\p"
	.string "Möchtest du mit Hilfe des Drahtlosen\n"
	.string "Kommunikations-Systems spielen?\p"
	.string "Bitte gedulde dich noch ein wenig!$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "In Ordnung! Komme wieder!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "Der Drahtlose Game Boy\n"
	.string "Advance-Adapter ist nicht\l"
	.string "angeschlossen.\p"
	.string "Komm wieder, wenn er\n"
	.string "angeschlossen ist!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "O.K., was wolltest du spielen?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Welches POKéMON soll teilnehmen?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Gut, du kannst loslegen!\n"
	.string "Lass nicht zu, dass dich die\l"
	.string "anderen besiegen!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Are you leaving now?\n"
	.string "Do come again!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Es scheint, dass keines deiner\n"
	.string "POKéMON teilnehmen kann…\p"
	.string "Soll ich dir erklären, welche\n"
	.string "POKéMON teilnehmen dürfen?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "Am “POKéMON-SPRUNG”\n"
	.string "dürfen POKéMON, die 70 cm oder\l"
	.string "kleiner sind, teilnehmen.\p"
	.string "POKéMON, die nicht springen können,\n"
	.string "dürfen nicht teilnehmen.\p"
	.string "Zum Beispiel POKéMON, die nur\n"
	.string "schwimmen, graben oder fliegen.\p"
	.string "Das ist schon alles!$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "“BEERENERNTE MIT DODRI”…\n"
	.string "Nur ein DODRI kann teilnehmen.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Could you retry this from the start\n"
	.string "again, please?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Willkommen im POKéMON\n"
	.string "DRAHTLOSEN DIREKTKLUB.\p"
	.string "Welchen KLUB möchtest du betreten?$"

CableClub_Text_TradePokemon:
	.string "Möchtest du jetzt POKéMON\n"
	.string "tauschen?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Welche Art des Kampfes?$"

CableClub_Text_AccessRecordCorner:
	.string "Möchtest du am STATISTIKTAUSCH\n"
	.string "teilnehmen?$"

CableClub_Text_UseBerryCrush:
	.string "Möchtest du die BEERENMÜHLE\n"
	.string "benutzen?$"

CableClub_Text_ExplainBattleModes:
	.string "Es gibt drei Kampfarten.\p"
	.string "EINZELKAMPF ist für zwei TRAINER,\n"
	.string "mit je einem oder\l"
	.string "mehreren POKéMON.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "ein POKéMON in den Kampf.\p"
	.string "DOPPELKAMPF ist für zwei TRAINER\n"
	.string "mit je zwei oder mehr PKMN.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "zwei POKéMON in den Kampf.\p"
	.string "MULTIKÄMPFE sind für vier TRAINER\n"
	.string "mit je einem oder mehreren PKMN.\p"
	.string "Jeder TRAINER schickt pro Runde\n"
	.string "ein POKéMON in den Kampf.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Bitte legt fest, wer von euch der\n"
	.string "LEITER ist.\p"
	.string "Der andere Spieler wählt\n"
	.string "“MITSPIELER” aus.$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Bitte legt fest, wer in eurem TEAM\n"
	.string "der LEITER ist.\p"
	.string "Die anderen Spieler wählen\n"
	.string "“MITSPIELER” aus.$"

CableClub_Text_ChooseGroupLeader:
	.string "Bitte legt fest, wer in eurem TEAM\n"
	.string "der LEITER ist.\p"
	.string "Die anderen Spieler wählen\n"
	.string "“MITSPIELER” aus.$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Willkommen im POKéMON DRAHTLOSEN\n"
	.string "KONNEX-KLUB.\p"
	.string "Du kannst hier direkt mit anderen\n"
	.string "TRAINERn interagieren, sogar\l"
	.string "mit unbekannten.\l"
	.string "Möchtest du den KLUB betreten?$"

CableClub_Text_UnionRoomInfo:
	.string "Die TRAINER im KONNEX-KLUB sind\n"
	.string "die Spieler, die ebenfalls den KLUB\l"
	.string "betreten haben.\p"
	.string "Hier kannst du alles Mögliche\n"
	.string "machen, z.B. Grußformeln\l"
	.string "austauschen!\l"
	.string "Du darfst zwei POKéMON bis\l"
	.string "Level 30 für einen Einzelkampf\l"
	.string "mitnehmen.\l"
	.string "Du kannst eine Unterhaltung mit\l"
	.string "zwei bis fünf Teilnehmern führen.\p"
	.string "Oder du meldest ein POKéMON zum\n"
	.string "Tausch an.\p"
	.string "Möchtest du den Klub betreten?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Ich hoffe, du genießt deinen\n"
	.string "Aufenthalt im KONNEX-KLUB.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Hallo!\n"
	.string "Ich bin TEALA.\p"
	.string "Dies scheint dein erstes Mal hier\n"
	.string "zu sein.\p"
	.string "Ich zeige dir, wie das Drahtlose\n"
	.string "Kommunikations-System funktioniert.\p"
	.string "Zunächst zeige ich dir dieses\n"
	.string "Stockwerk unseres POKéMON-\l"
	.string "CENTERs.\p"
	.string "Hier entlang bitte!$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Im Obergeschoss gibt es zwei\n"
	.string "KLUBs.\p"
	.string "Zum Ersten den KLUB links.\n"
	.string "Das ist der KONNEX-KLUB.\p"
	.string "Hier kannst du TRAINER treffen, die\n"
	.string "ebenfalls den KONNEX-KLUB\l"
	.string "betreten haben.\p"
	.string "Du kannst mit ihnen sprechen,\n"
	.string "kämpfen und tauschen.\p"
	.string "Zum Zweiten den KLUB rechts.\n"
	.string "Das ist der DIREKTKLUB.\p"
	.string "Hier kannst du mit POKéMON gegen\n"
	.string "Freunde kämpfen oder sie tauschen.\p"
	.string "Falls der Drahtlose Game Boy\n"
	.string "Advance-Adapter nicht\l"
	.string "eingesteckt ist, kannst du das\l"
	.string "GBA Game Link-Kabel benutzen.\p"
	.string "In diesem Fall musst du den\n"
	.string "DIREKTKLUB betreten.\p"
	.string "Viel Vergnügen mit dem Drahtlosen\n"
	.string "Kommunikations-System.$"

CableClub_Text_AskAboutLinking:
	.string "Hallo {PLAYER}!\p"
	.string "Ich bin es, TEALA, die Angestellte\n"
	.string "vom 1. Stock im POKéMON-CENTER.\p"
	.string "Möchtest du mich etwas über das\n"
	.string "Herstellen einer Verbindung fragen?$"

CableClub_Text_ExplainWirelessClub:
	.string "Ich erkläre dir, wie der POKéMON\n"
	.string "DRAHTLOSKLUB funktioniert.\p"
	.string "Im Obergeschoss gibt es zwei\n"
	.string "KLUBs.\p"
	.string "Zum Ersten den linken KLUB.\n"
	.string "Das ist der KONNEX-KLUB.\p"
	.string "Hier kannst du TRAINER treffen, die\n"
	.string "ebenfalls den KONNEX-KLUB\l"
	.string "betreten haben.\p"
	.string "Du kannst mit ihnen sprechen,\n"
	.string "kämpfen und tauschen.\p"
	.string "Zum Zweiten den KLUB rechts.\n"
	.string "Das ist der DIREKTKLUB.\p"
	.string "Hier kannst du mit POKéMON gegen\n"
	.string "Freunde kämpfen oder sie tauschen.\p"
	.string "Manchmal kannst du deine\n"
	.string "Freunde in keinem der KLUBs\l"
	.string "treffen.\p"
	.string "In diesem Fall musst du näher\n"
	.string "zu deinen Freunden rücken.\p"
	.string "Falls der Drahtlose Game Boy\n"
	.string "Advance-Adapter nicht\l"
	.string "benutzt wird, kannst\l"
	.string "du via Game Boy Advance\l"
	.string "Game Link-Kabel eine\l"
	.string "Verbindung herstellen.\p"
	.string "In diesem Fall musst du in\n"
	.string "den DIREKTKLUB gehen.\p"
	.string "Viel Vergnügen mit dem Drahtlosen\n"
	.string "Kommunikations-System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Viel Vergnügen mit dem Drahtlosen\n"
	.string "Kommunikations-System.$"
