gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} von {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "CONTEST$"

gContestRankNormal::
	.string "NORMAL-KLASSE$"

gContestRankSuper::
	.string "SUPER-KLASSE$"

gContestRankHyper::
	.string "HYPER-KLASSE$"

gContestRankMaster::
	.string "MASTER-KLASSE$"

gContestLink::
	.string "LINK$"

gContestCoolness::
	.string "COOL.$"

gContestBeauty::
	.string "SCHÖN.$"

gContestCuteness::
	.string "ANMUT$"

gContestSmartness::
	.string "KLUG.$"

gContestToughness::
	.string "STÄRKE$"

gContestPaintingCool1::
	.string "Super-mega-cool ist\n"
	.string "dieses umwerfende {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Das anbetungswürdige\n"
	.string "POKéMON: {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Phantastisch, großartig -\n"
	.string "schlicht brillant: {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "Ein Bild von einem POKéMON!\n"
	.string "Das wunderschöne {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "Einfach umwerfend, das strahlende\n"
	.string "Lächeln von {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "Superstar des POKéMON-CENTERs -\n"
	.string "das unvergleichliche {STR_VAR_1}$"

gContestPaintingCute1::
	.string "Das liebliche, zuckersüße {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Das Gewinner-Portrait\n"
	.string "von dem hübschen {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Winke uns zu, du\n"
	.string "goldiges {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Der Gelehrte unter den\n"
	.string "POKéMON! Das weise {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "Das auserwählte und\n"
	.string "einzigartige POKéMON: {STR_VAR_1}$"

gContestPaintingSmart3::
	.string "Das grandiose {STR_VAR_1},\n"
	.string "der Inbegriff von Eleganz und Stil$"

gContestPaintingTough1::
	.string "Der energische, kraftstrotzende\n"
	.string "Überflieger: {STR_VAR_1}$"

gContestPaintingTough2::
	.string "Stark, stärker, am stärksten -\n"
	.string "das allerstärkste {STR_VAR_1}$"

gContestPaintingTough3::
	.string "Das mächtige, prächtige - das\n"
	.string "stärkste POKéMON: {STR_VAR_1}$"
