@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Eine sehr ansprechende\n"
	.string "Vorführung.$"

gText_UserMoreEasilyStartled::
	.string "Einsatz der Attacke macht\n"
	.string "PKMN leichter irritierbar.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Großartiger Ausdruck, der\n"
	.string "sich nicht steigern lässt.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Langweilt den JUROR auch\n"
	.string "bei Wiederholung nicht.$"

gText_AvoidStartledByOthersOnce::
	.string "Kann Irritation durch\n"
	.string "andere einmal verhindern.$"

gText_AvoidStartledByOthers::
	.string "Kann Irritation durch\n"
	.string "andere verhindern.$"

gText_AvoidStartledByOthersLittle::
	.string "Kann Irritation durch an-\n"
	.string "dere ein wenig eindämmen.$"

gText_UserLessLikelyStartled::
	.string "Einsatz der Attacke dämmt\n"
	.string "danach Irritation ein.$"

gText_SlightlyStartleFrontMon::
	.string "Irritiert das vordere\n"
	.string "POKéMON ein wenig.$"

gText_SlightlyStartleAppealed::
	.string "Irritiert die POKéMON ein\n"
	.string "wenig, die schon auftraten.$"

gText_StartleAppealedBeforeUser::
	.string "Irritiert das POKéMON, das\n"
	.string "vorher aufgetreten ist.$"

gText_StartleAllAppealed::
	.string "Irritiert alle POKéMON,\n"
	.string "die bisher auftraten.$"

gText_BadlyStartleFrontMon::
	.string "Irritiert das vordere\n"
	.string "POKéMON sehr stark.$"

gText_BadlyStartleAppealed::
	.string "Irritiert die POKéMON, die\n"
	.string "schon aufgetreten sind.$"

gText_StartleAppealedBeforeUser2::
	.string "Irritiert das POKéMON, das\n"
	.string "vorher aufgetreten ist.$"

gText_StartleAllAppealed2::
	.string "Irritiert alle POKéMON, die\n"
	.string "vorher aufgetreten sind.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Lenkt den JUROR von den\n"
	.string "anderen POKéMON ab.$"

gText_StartleMonHasJudgesAttention::
	.string "Irritiert PKMN, bes. die,\n"
	.string "auf die der JUROR achtet.$"

gText_JamOthersMissesTurn::
	.string "Stört die anderen und An-\n"
	.string "wender setzt 1 Runde aus.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Irritiert PKMN, bes. die, die\n"
	.string "Ausdruck gl. Typs zeigten.$"

gText_BadlyStartleCoolAppeals::
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs COOL vorführten.$"

gText_BadlyStartleBeautyAppeals::
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs SCHÖN vorführten.$"

gText_BadlyStartleCuteAppeals::
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs ANMUT vorführten.$"

gText_BadlyStartleSmartAppeals::
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs KLUG vorführten.$"

gText_BadlyStartleToughAppeals::
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs STARK vorführten.$"

gText_MakeMonAfterUserNervous::
	.string "Macht nachfolgendes\n"
	.string "POKéMON nervös.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Macht alle nachfolgenden\n"
	.string "POKéMON nervös.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Schwächt Kondition der\n"
	.string "PKMN, die bisher auftraten.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Irritiert POKéMON, die eine\n"
	.string "gute Kondition haben.$"

gText_AppealGreatIfPerformedFirst::
	.string "Ausdruck gelingt sehr gut,\n"
	.string "wenn als Erster vorgeführt.$"

gText_AppealGreatIfPerformedLast::
	.string "Ausdruck gelingt sehr gut,\n"
	.string "wenn zuletzt vorgeführt.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Ausdruck gelingt so gut\n"
	.string "wie die der Vorgänger.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Ausdruck gelingt so gut\n"
	.string "wie der des Vorgängers.$"

gText_AppealBetterLaterItsPerformed::
	.string "Je später der Auftritt,\n"
	.string "desto besser der Ausdruck.$"

gText_AppealVariesDependingOnTiming::
	.string "Die Qualität des Ausdrucks\n"
	.string "hängt vom Timing ab.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Gelingt gut, wenn vom\n"
	.string "selben Typ wie der vorige.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Gelingt gut, wenn vom\n"
	.string "anderen Typ als der vorige.$"

gText_AffectedByAppealInFront::
	.string "Hängt von Qualität des\n"
	.string "Ausdrucks d. Vorgängers ab.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Verbessert die Kondition\n"
	.string "und verhindert Nervosität.$"

gText_AppealWorksWellIfConditionGood::
	.string "Ausdruck gelingt gut, wenn\n"
	.string "Kondition des PKMN gut ist.$"

gText_NextAppealMadeEarlier::
	.string "Der nächste Ausdruck kann\n"
	.string "früher vorgeführt werden.$"

gText_NextAppealMadeLater::
	.string "Der nächste Ausdruck kann\n"
	.string "später vorgeführt werden.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Ändert die Reihenfolge der\n"
	.string "nächst. Auftritte leichter.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Ändert die Reihenfolge der\n"
	.string "nächsten Auftritte.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Verzückt das Publikum in \n"
	.string "jedem WETTBEWERB.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Irritiert alle POKéMON,\n"
	.string "deren Ausdruck gut war.$"

gText_AppealBestMoreCrowdExcited::
	.string "Gelingt am besten, wenn\n"
	.string "das Publikum gespannt ist.$"

gText_TemporarilyStopCrowdExcited::
	.string "Bremst zeitweise Begeis-\n"
	.string "terung des Publikums.$"

@ Unused move names

gText_RainDance::
	.string "REGENTANZ$"

gText_Rage::
	.string "RASEREI$"

gText_FocusEnergy::
	.string "ENERGIEFOKUS$"

gText_Hypnosis::
	.string "HYPNOSE$"

gText_Softboiled::
	.string "WEICHEI$"

gText_HornAttack::
	.string "HORNATTACKE$"

gText_SwordsDance::
	.string "SCHWERTTANZ$"

gText_Conversion::
	.string "UMWANDLUNG$"

gText_SunnyDay::
	.string "SONNENTAG$"

gText_Rest2::
	.string "ERHOLUNG$"

gText_Vicegrip::
	.string "KLAMMER$"

gText_DefenseCurl::
	.string "EINIGLER$"

gText_LockOn::
	.string "ZIELSCHUSS$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL.$"

gContestMoveTypeBeautyText::
	.string "SCHÖN.$"

gContestMoveTypeCuteText::
	.string "ANMUT$"

gContestMoveTypeSmartText::
	.string "KLUG.$"

gContestMoveTypeToughText::
	.string "STÄRKE$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Ausdruck {STR_VAR_1}! Welche\n"
	.string "Attacke wird gezeigt?$"

gText_AppealNumButItCantParticipate::
	.string "Ausdruck {STR_VAR_1}! Aber es\n"
	.string "kann nicht teilnehmen!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} führt\n"
	.string "{STR_VAR_2} vor!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} beobachtet\n"
	.string "die anderen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "Soweit zur\n"
	.string "Ausdruckskraft!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Der Auftritt\n"
	.string "wurde gestört.$"

gText_FollowedAnotherMonsLead::
	.string "Es folgte einem\n"
	.string "anderen POKéMON.$"

gText_ButItMessedUp::
	.string "Es scheiterte.$"

gText_WentBetterThanUsual::
	.string "Das lief besser\n"
	.string "als sonst.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Der JUROR war\n"
	.string "irgendwie abgelenkt.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Es strengte sich an,\n"
	.string "Fehler auszubügeln.$"

gText_CantMakeAnyMoreMoves::
	.string "Es kann keine Attacken\n"
	.string "mehr ausführen.$"

gText_WorkedFrighteninglyWell::
	.string "Das lief unheimlich gut.$"

gText_WorkedHardAsStandoutMon::
	.string "Es strengte sich genauso\n"
	.string "wie das beste POKéMON an.$"

gText_JudgedLookedOnExpectantly::
	.string "Der JUROR schaute es\n"
	.string "besonders aufmerksam an.$"

gText_WorkedRatherWell::
	.string "Das lief bedeutend\n"
	.string "besser.$"

gText_WorkedLittleBetterThanUsual::
	.string "Es lief etwas besser\n"
	.string "als sonst.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} stach\n"
	.string "überhaupt nicht hervor…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} stach nicht\n"
	.string "besonders hervor…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} erregte ein\n"
	.string "wenig Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} erregte eine\n"
	.string "Menge Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} erhielt die\n"
	.string "volle Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} konnte\n"
	.string "keinen Ausdruck zeigen.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "Der JUROR behält\n"
	.string "{STR_VAR_1} fest im Blick.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_3} von {STR_VAR_1}\n"
	.string "ändert die Wahrnehmung.$"

gText_MonsAppealEffectWoreOff::
	.string "Wirkung von {STR_VAR_1}\n"
	.string "lässt nach.$"

gText_SpecialAppealsEffectWoreOff::
	.string "Die besondere Wirkung\n"
	.string "lässt nach.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Jeder Ausdruck wird sich\n"
	.string "nun gleichen.$"

gText_CheapenedMonsAppeal::
	.string "Ausdruck von {STR_VAR_2}\n"
	.string "wurde abgewertet.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Es wertete die Ausdrücke\n"
	.string "der anderen PKMN ab.$"

gText_StoleAttentionAwayFromMon::
	.string "Es stahl {STR_VAR_2} die\n"
	.string "Aufmerksamkeit.$"

gText_CheapenedMonsAppeal2::
	.string "Ausdruck von {STR_VAR_2}\n"
	.string "wurde abgewertet.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "Es wertete die Ausdrücke\n"
	.string "der anderen stark ab.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Heiß ersehnt: Der Aus-\n"
	.string "druck von {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Es wertete den Ausdruck\n"
	.string "der PKMN vor ihm ab.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Es wertete den Lieblings-\n"
	.string "ausdruck des JURORS ab.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Der Ausdruckswert der\n"
	.string "anderen wurde halbiert.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Es macht sich bereit, die\n"
	.string "anderen zu beeindrucken.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Es kann an keiner Vor-\n"
	.string "führung mehr teilnehmen.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Der fantastische Aus-\n"
	.string "druck berührte den JUROR.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Die Erwartung für die fol-\n"
	.string "genden Ausdrücke steigt.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Es war so beeindruckend\n"
	.string "wie ein Spezialausdruck.$"

gText_StoodOutAsMuchAsMon::
	.string "Es war so beeindruckend\n"
	.string "wie {STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Ein Ausdruck, der gestört\n"
	.string "wurde, ist unauffälliger.$"

gText_EveryonesAppealsMadeSame::
	.string "Jeder Teilnehmer hat nun\n"
	.string "den gleichen Ausdruck.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Es wird sich der anderen\n"
	.string "PKMN mehr bewusst.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} kann danach\n"
	.string "keinen Ausdruck zeigen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Es kommt ein wenig\n"
	.string "zur Ruhe.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Die anderen PKMN nehmen\n"
	.string "es überhaupt nicht wahr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Es ist sich der anderen\n"
	.string "PKMN kaum bewusst.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Es kümmert sich nicht\n"
	.string "mehr viel um andere PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Es versucht, die anderen\n"
	.string "PKMN zu blenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Der JUROR schaut\n"
	.string "{STR_VAR_1} nicht mehr an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Es versucht, d. folgenden\n"
	.string "PKMN zu entnerven.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} wird\n"
	.string "nervös.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Dieser Ausdruck soll die\n"
	.string "anderen PKMN entnerven.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Es verhöhnt die\n"
	.string "besseren PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} findet zu\n"
	.string "seiner Form zurück.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Es versucht, die besseren\n"
	.string "PKMN zu beeindrucken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{STR_VAR_1} an der Spitze\n"
	.string "engagiert sich noch mehr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Das bisher unauffällige\n"
	.string "{STR_VAR_1} gibt alles.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Es strengt sich genauso\n"
	.string "an wie die PKMN vor ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam nicht gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Es strengt sich an wie die\n"
	.string "vorangegangenen PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war absolut mies.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war sehr gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Der gleiche Typ wie das\n"
	.string "vorhergehende PKMN. Gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Nicht der gleiche Typ wie\n"
	.string "das vorherige PKMN - gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Es ist viel besser als die\n"
	.string "vorhergehenden PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Es war nicht so gut wie\n"
	.string "das PKMN vor ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "Die Kondition von\n"
	.string "{STR_VAR_1} stieg.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Status von {STR_VAR_1}:\n"
	.string "Bewirkt guten Ausdruck!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Es steigt in der Reihen-\n"
	.string "folge auf.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Es fällt in der Reihen-\n"
	.string "folge zurück.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Es bringt die Reihenfolge\n"
	.string "durcheinander.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Der JUROR betrachtet\n"
	.string "{STR_VAR_1} interessiert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "Die Combo der Ausdrücke\n"
	.string "kam gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "Die Combo der Ausdrücke\n"
	.string "kam sehr gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "Die Combo der Ausdrücke\n"
	.string "kam exzellent an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} gelingt es,\n"
	.string "den Blick abzuwenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} wandte den\n"
	.string "Blick erfolgreich ab.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} lässt sich\n"
	.string "davon nicht ablenken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} wurde etwas\n"
	.string "unruhig.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} blickt\n"
	.string "irritiert zu Boden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} dreht sich\n"
	.string "irritiert um.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} kann einen \n"
	.string "Laut nicht unterdrücken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} kann nicht\n"
	.string "anders und springt auf.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} ist so irri-\n"
	.string "tiert, dass es stolpert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} ist zu nervös,\n"
	.string "um etwas vorzuführen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "Es hatte keinen Erfolg.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Es konnte keine\n"
	.string "Nervosität erzeugen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Aber es konnte niemanden\n"
	.string "nervös machen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "Es wurde ignoriert…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "Es konnte seinen Aus-\n"
	.string "druck nicht verstärken…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Schwacher Ausdruck we-\n"
	.string "gen schlechter Kondition.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} blieb\n"
	.string "unbeeindruckt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} enttäuscht\n"
	.string "durch Wiederholung.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war sehr gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war nicht gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1} begeistert\n"
	.string "Publikum mit {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} setzt in der \n"
	.string "folgenden Runde aus.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "Die Aufmerksamkeit des\n"
	.string "Publikums liegt auf ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "Das Publikum beobachtet\n"
	.string "weiterhin {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2} von\n"
	.string "{STR_VAR_1} sah keiner.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "Scheu$"

gText_Contest_Anxiety::
	.string "Besorgnis$"

gText_Contest_Laziness::
	.string "Faulheit$"

gText_Contest_Hesitancy::
	.string "Zögern$"

gText_Contest_Fear::
	.string "Furcht$"

gText_Contest_Coolness::
	.string "Coolness$"

gText_Contest_Beauty::
	.string "Schönheit$"

gText_Contest_Cuteness::
	.string "Anmut$"

gText_Contest_Smartness::
	.string "Klugheit$"

gText_Contest_Toughness::
	.string "Stärke$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "COOLE Att.$"

gText_BeautyMove::
	.string "SCHÖNE Att.$"

gText_CuteMove::
	.string "ANMUT-Att.$"

gText_SmartMove::
	.string "KLUGE Att.$"

gText_ToughMove::
	.string "STARKE Att.$"

gText_3QuestionMarks::
	.string "{STR_VAR_1}$"
