@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Missed turn$"

gText_LinkStandby4::
	.string "Verbindung…$"

gText_WinnerIsPlayersMonCongrats::
	.string "The winner is {STR_VAR_1}’s {STR_VAR_2}!\n"
	.string "Congratulations!$"

gText_WinnerIsPlayersMon::
	.string "Gewinner: {STR_VAR_2} von {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Erstes Urteil: Nr. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Zweites Urteil: Nr. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Event Nr. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Attacke, die am häufigsten eingesetzt\n"
	.string "wurde: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "Das beeindruckendste POKéMON:\n"
	.string "{STR_VAR_2} von {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Event Nr. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Der TRAINER hat verloren, daher wird\n"
	.string "kein TV-Programm gesendet.$"
