@ Battle Tower
gText_AnabelWonSilver::
	.string "Das war sehr enttäuschend…$"

gText_AnabelDefeatSilver::
	.string "Ich sehe schon…$"

gText_AnabelWonGold::
	.string "Das tut mir sehr Leid…$"

gText_AnabelDefeatGold::
	.string "Vielen Dank…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahahaha! Ist dir das nicht mehr als\n"
	.string "peinlich? Und das vor den Augen aller!$"

gText_TuckerDefeatSilver::
	.string "Grrr…\n"
	.string "Was war…$"

gText_TuckerWonGold::
	.string "Mein STADIONSTAR-Titel ist nicht\n"
	.string "nur Show!$"

gText_TuckerDefeatGold::
	.string "Ahahahaha!\n"
	.string "Wie erfrischend und inspirierend!!!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Du hast noch viel Arbeit vor dir! Aber\n"
	.string "das war doch eine gute Übung, oder?$"

gText_NolandDefeatSilver::
	.string "Gut gemacht!\n"
	.string "Du weißt genau, was du willst!$"

gText_NolandWonGold::
	.string "Hey, hey, hey!\n"
	.string "Das war’s schon? Ging ja schnell!$"

gText_NolandDefeatGold::
	.string "Was war das denn?!?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Hmpf…$"

gText_LucyDefeatSilver::
	.string "Argh…$"

gText_LucyWonGold::
	.string "Hah!$"

gText_LucyDefeatGold::
	.string "Mist!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Ach, mach schon!\n"
	.string "Streng dich mal ein bisschen an!$"

gText_GretaDefeatSilver::
	.string "Das gibt’s ja nicht!\n"
	.string "Klasse gemacht!$"

gText_GretaWonGold::
	.string "Hähähä!\n"
	.string "Hast du was anderes erwartet?!?$"

gText_GretaDefeatGold::
	.string "Was?\n"
	.string "Das ist jetzt nicht dein Ernst, oder?$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Deine POKéMON passen zu dir! Sie\n"
	.string "sind genauso jämmerlich wie du!$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Nun... äh, das war unerwartet…$"

gText_SpenserWonGold::
	.string "Muahahahaha… Wir haben nichts zu\n"
	.string "befürchten! Uns kann keiner was!$"

gText_SpenserDefeatGold::
	.string "Muahahaha!\n"
	.string "Hahahaha!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hey! Was ist los mit dir?\n"
	.string "Zeig, was du kannst! Hopp hopp!$"

gText_BrandonDefeatSilver::
	.string "Das ist wahrer Kampfgeist! Sehr gut!\n"
	.string "Du hast dich wirklich angestrengt!$"

gText_BrandonWonGold::
	.string "Hey! Du kannst doch nicht einfach\n"
	.string "aufgeben! Du musst an dich glauben!$"

gText_BrandonDefeatGold::
	.string "Jawohl! Du hast es geschafft!\n"
	.string "Gut, dass du niemals aufgegeben hast!$"
