gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRK: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem POKéDEX zeigen?$"

gBirchDexRatingText_Cancel::
	.string "Ach? Du hast erst so wenige\n"
	.string "POKéMON gefangen, dass es sich\l"
	.string "nicht lohnt, ihn mir zu zeigen?$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Oh, du hast {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen…$"

gBirchDexRatingText_LessThan10::
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf POKéMON\l"
	.string "achten.$"

gBirchDexRatingText_LessThan20::
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"

gBirchDexRatingText_LessThan30::
	.string "Einige POKéMON tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"

gBirchDexRatingText_LessThan40::
	.string "Nun, er könnte mehr Einträge\n"
	.string "enthalten, aber es sieht schon\l"
	.string "eher nach einem POKéDEX aus.$"

gBirchDexRatingText_LessThan50::
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"

gBirchDexRatingText_LessThan60::
	.string "Verwendest du irgendwelche\n"
	.string "ANGELn?\l"
	.string "Hier gibt es viele POKéMON im Meer.$"

gBirchDexRatingText_LessThan70::
	.string "Statt die POKéMON nur zu fangen,\n"
	.string "wie wäre es, sie sich entwickeln zu\l"
	.string "lassen?$"

gBirchDexRatingText_LessThan80::
	.string "Der POKéDEX wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"

gBirchDexRatingText_LessThan90::
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"

gBirchDexRatingText_LessThan100::
	.string "Warst du schon mal in der\n"
	.string "SAFARI-ZONE?\p"
	.string "Ich habe gehört, es gibt POKéMON,\n"
	.string "die man nur dort finden kann.$"

gBirchDexRatingText_LessThan110::
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "Es gibt auch POKéMON, die man\n"
	.string "durch den Einsatz von\l"
	.string "ZERTRÜMMERER findet.$"

gBirchDexRatingText_LessThan130::
	.string "Du solltest einige POKéMON fangen\n"
	.string "und sie mit anderen tauschen.$"

gBirchDexRatingText_LessThan140::
	.string "Ich habe von POKéMON gehört, die\n"
	.string "sich entwickeln, wenn sie ihren\l"
	.string "TRAINER sehr lieben.$"

gBirchDexRatingText_LessThan150::
	.string "Ich hatte keine Ahnung, dass es in\n"
	.string "der HOENN-Region so viele\l"
	.string "verschiedene POKéMON-Arten gibt.$"

gBirchDexRatingText_LessThan160::
	.string "Manchmal erscheinen einige\n"
	.string "POKéMON in großer Anzahl\p"
	.string "wie bei einem Ausbruch.\n"
	.string "Das solltest du nicht verpassen!$"

gBirchDexRatingText_LessThan170::
	.string "Dein POKéDEX liefert einen\n"
	.string "erstaunlich guten Einblick in die\l"
	.string "POKéMON der HOENN-Region!$"

gBirchDexRatingText_LessThan180::
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter POKéMON-PROFESSOR\l"
	.string "qualifiziert.$"

gBirchDexRatingText_LessThan190::
	.string "Mit diesem POKéDEX, der schon so\n"
	.string "weit gediehen ist, bist du ein\l"
	.string "echter Profi.$"

gBirchDexRatingText_LessThan200::
	.string "Du bist sehr nahe dran, den\n"
	.string "POKéDEX zu vervollständigen.\l"
	.string "Das fühle ich einfach.$"

gBirchDexRatingText_DexCompleted::
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein POKéDEX ist vollständig!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen…$"
