OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Das POKéMON auf der linken Seite der\n"
	.string "Liste tritt im Kampf als Erstes an.\p"
	.string "Hast du mehrere POKéMON in deinem Team,\n"
	.string "stelle sie so der Reihe nach auf, wie es\l"
	.string "für den Kampf am günstigsten ist.\p"
	.string "Das kann ein Vorteil für dich sein.$"

